nav:
    - Introduction: index.md
    - Learning-git-branch: Learning-git-branch
    - git-mechanism: git-mechanism
    - Pro-Git: Pro-Git
    - Reference: Reference
    - Submodule: Submodule
    - Delete-commit: Delete-commit
    - 大小写: 大小写
    - Workflow: Workflow
    - Errors: Errors    
    - Sourcetree: Sourcetree
    