nav:
    - Introduction: index.md
    - git-clone: git-clone
    - Sharing&updating-project: Sharing&updating-project
    - Patching: Patching
    - git-merge&rebase: git-merge&rebase
    - Plumbing-Commands: Plumbing-Commands
    - git-current-branch: git-current-branch
    - git-undo: git-undo
    