nav:
    - Introduction: index.md
    - Branching-and-Merging: Branching-and-Merging
    - git-clone: git-clone
    - Sharing&updating-project: Sharing&updating-project
    - Patching: Patching
    - Plumbing-Commands: Plumbing-Commands
    - git-current-branch: git-current-branch
    - git-undo: git-undo
    