edit_uri: ''
extra_css:
- css/extra.css
extra_javascript:
- https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML
google_analytics:
- UA-27795084-5
- mkdocs.org
markdown_extensions:
- toc:
    separator: '#'
- admonition
- def_list
- mdx_gh_links:
    repo: mkdocs
    user: mkdocs
- pymdownx.arithmatex
- pymdownx.betterem:
    smart_enable: all
- pymdownx.caret
- pymdownx.critic
- pymdownx.details
- pymdownx.inlinehilite
- pymdownx.magiclink
- pymdownx.mark
- pymdownx.smartsymbols
- pymdownx.superfences
- pymdownx.tasklist:
    custom_checkbox: true
- pymdownx.tilde
nav:
- Introduction: index.md
- Software-engineering:
  - Introduction: Software-engineering/index.md
- Software-quality:
  - Introduction: Software-quality/index.md
  - Reusability:
    - Introduction: Software-quality/Reusability/index.md
  - Readability:
    - Introduction: Software-quality/Readability/index.md
- Software-requirements:
  - Introduction: 0Requirements/index.md
- Software-design:
  - Introduction: 1Design/index.md
  - Principle:
    - Introduction: 1Design/Principle/index.md
    - Abstraction:
      - Abstraction-in-software-design: 1Design/Principle/Abstraction/Abstraction-in-software-design.md
    - Control-theory:
      - Introduction: 1Design/Principle/Control-theory/index.md
      - Inversion-of-control:
        - Introduction: 1Design/Principle/Control-theory/Inversion-of-control/index.md
        - wikipedia-Inversion-of-control: 1Design/Principle/Control-theory/Inversion-of-control/wikipedia-Inversion-of-control.md
        - tutorialsteacher-Inversion-of-Control: 1Design/Principle/Control-theory/Inversion-of-control/tutorialsteacher-Inversion-of-Control.md
      - TODO-Control-dependency:
        - Introduction: 1Design/Principle/Control-theory/TODO-Control-dependency/index.md
    - Information-hiding:
      - Introduction: 1Design/Principle/Information-hiding/index.md
      - Transparency:
        - Introduction: 1Design/Principle/Information-hiding/Transparency/index.md
  - Commonality-and-variability-analysis:
    - Introduction: 1Design/Commonality-and-variability-analysis/index.md
  - Decompose-and-assemble:
    - Introduction: 1Design/Decompose-and-assemble/index.md
  - Design-pattern:
    - Introduction: 1Design/Design-pattern/index.md
    - Architecture-pattern:
      - Introduction: 1Design/Design-pattern/Architecture-pattern/index.md
      - Plugin-architecture:
        - Introduction: 1Design/Design-pattern/Architecture-pattern/Plugin-architecture/index.md
        - Component-based-software-engineering: 1Design/Design-pattern/Architecture-pattern/Plugin-architecture/Component-based-software-engineering.md
      - Monolithic-and-micro:
        - Introduction: 1Design/Design-pattern/Architecture-pattern/Monolithic-and-micro/index.md
      - Middleware:
        - Introduction: 1Design/Design-pattern/Architecture-pattern/Middleware/index.md
        - Message-oriented-middleware: 1Design/Design-pattern/Architecture-pattern/Middleware/Message-oriented-middleware.md
      - Service-oriented-architecture:
        - Introduction: 1Design/Design-pattern/Architecture-pattern/Service-oriented-architecture/index.md
        - Microservice:
          - Introduction: 1Design/Design-pattern/Architecture-pattern/Service-oriented-architecture/Microservice/index.md
      - Task-model:
        - Introduction: 1Design/Design-pattern/Architecture-pattern/Task-model/index.md
        - Schedule:
          - Introduction: 1Design/Design-pattern/Architecture-pattern/Task-model/Schedule/index.md
          - Priority-inversion:
            - Introduction: 1Design/Design-pattern/Architecture-pattern/Task-model/Schedule/Priority-inversion/index.md
      - Multilayered-architecture:
        - Introduction: 1Design/Design-pattern/Architecture-pattern/Multilayered-architecture/index.md
        - Abstraction-and-architecture-and-layer: 1Design/Design-pattern/Architecture-pattern/Multilayered-architecture/Abstraction-and-architecture-and-layer.md
        - Book-code-reading:
          - Introduction: 1Design/Design-pattern/Architecture-pattern/Multilayered-architecture/Book-code-reading/index.md
    - Pool:
      - Introduction: 1Design/Design-pattern/Pool/index.md
      - Prefork-process-pool:
        - Introduction: 1Design/Design-pattern/Pool/Prefork-process-pool/index.md
      - Memory-pool:
        - Introduction: 1Design/Design-pattern/Pool/Memory-pool/index.md
        - C++Memory-Pool-CTable: 1Design/Design-pattern/Pool/Memory-pool/C++Memory-Pool-CTable.md
      - Connection-pool:
        - Introduction: 1Design/Design-pattern/Pool/Connection-pool/index.md
  - Experience: 1Design/Experience.md
  - UML:
    - Introduction: 1Design/UML/index.md
- Software-development:
  - Introduction: 2Development/index.md
  - Development-process:
    - Introduction: 2Development/Development-process/index.md
    - TDD&BDD:
      - Introduction: 2Development/Development-process/TDD&BDD/index.md
      - TDD:
        - Introduction: 2Development/Development-process/TDD&BDD/TDD/index.md
      - BDD:
        - Introduction: 2Development/Development-process/TDD&BDD/BDD/index.md
  - Configuration-management:
    - Introduction: 2Development/Configuration-management/index.md
  - Software-build:
    - Introduction: 2Development/Software-build/index.md
  - QA:
    - Introduction: 2Development/QA/index.md
  - "\u8D28\u91CF\u63D0\u5347":
    - Introduction: "2Development/\u8D28\u91CF\u63D0\u5347/index.md"
- Software-distribution:
  - Introduction: 3Distribution/index.md
  - Software-release-life-cycle: 3Distribution/Software-release-life-cycle.md
- TODO-Software-analysis:
  - Introduction: TODO-Software-analysis/index.md
- DevOps:
  - Introduction: DevOps/index.md
  - 12factor:
    - Introduction: DevOps/12factor/index.md
plugins:
- search
repo_url: https://github.com/dengking/software-engineering
site_author: DengKing
site_description: Project documentation with Markdown.
site_name: software-engineering
site_url: https://dengking.github.io/software-engineering
theme:
  name: material
