nav:
    - Introduction: index.md
    - Principle: Principle
    - Commonality&variability-analysis: Commonality&variability-analysis
    - Decompose&assemble: Decompose&assemble
    - Design-pattern: Design-pattern
    - Experience: Experience.md
    - UML: UML
    