nav:
    - Introduction: index.md
    - Plugin-architecture: Plugin-architecture
    - Monolithic-VS-micro: Monolithic-VS-micro
    - Middleware: Middleware
    - Service-oriented-architecture: Service-oriented-architecture
    - Task-model: Task-model
    - Multilayered-architecture: Multilayered-architecture
    