nav:
    - Introduction: index.md
    - Plugin-architecture: Plugin-architecture
    - Monolithic-and-micro: Monolithic-and-micro
    - Middleware: Middleware
    - Service-oriented-architecture: Service-oriented-architecture